config/routes.rb
Rails.application.routes.draw do

  namespace :resource do
    resources :subjects
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'set_language/kyrgyz'

  get 'set_language/russian'

  get 'home/index'

  resources :forums, only: [:index, :new] do
    resources :questions do
      collection do
        post :vote_question_up
        post :vote_question_down
      end
      resources :answers,:comments do
        collection do
          post :vote_answer_up
          post :vote_answer_down
        end
        resources :answer_comments
      end
    end
  end



  resources :orts
  resources :profiles do
    collection do
      get :math
      get :analogy
      get :grammar
      get :reading
    end
  end

  namespace :ort do
    resources :infos

    resources :mains do
      collection do
        get :kolonka
        get :algebra
        get :analogy
        get :reading
        get :grammar
        get :email_ort
        post :check_reading
        post :check_kolonka
        post :check_algebra
        post :check_analogy
        post :check_grammar
        get :previous_grammar
        get :previous_reading
        get :previous_analogy
        get :previous_kolonka
        get :previous_algebra
        get :result
        get :start_over
      end
    end

    resources :grammar_quizzes do
      collection do
        post :check_grammar
        get :result
        get :previous_grammar
        get :start_over
      end
    end

    resources :reading_quizzes do
      collection do
        post :check_reading
        get :result
        get :previous_reading
        get :start_over
      end
    end

    resources :analogy_quizzes do
      collection do
        post :check_analogy
        get :result
        get :previous_analogy
        get :start_over
      end
    end

    resources :mathematic_quizzes do
      collection do
        post :check_part_one
        post :check_part_two
        get :result
        get :start_over
        get :home_page
        get :part_one
        get :part_two
        get :previous_part_one
        get :previous_part_two
      end
    end
  end

  devise_for :users, :controllers =>  { :omniauth_callbacks => "users/omniauth_callbacks" } do
    root 'admin'
  end

  as :user do
    get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
  end

  root to: 'home#index'
end

app/views/shared/_header.html.erb
<!--

<% unless user_signed_in? %>

  <p>
    <%= link_to_unless I18n.locale == :kg, "Кыргыз", set_language_kyrgyz_path %>
    |

     <%= link_to_unless I18n.locale == :ru, "Русский",set_language_russian_path%>
  </p>

    <% end %>

  <div class="navbar navbar-custom navbar-static-top">

    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to t('navbar.name'),root_url,class: 'navbar-brand'%>


      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><%= t('navbar.home')%></a></li>
          <li><a><%= t('navbar.answer') %></a> </li>
          <li class="dropdown open megamenu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.course') %> <span class="caret"></span></a>
            <div class="dropdown-menu">
              <ul class="list-unstyled col-lg-3 col-sm-6" role="menu">
                <li><h3>Start</h3></li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more link</a></li>
              </ul>
              <ul class="nav col-lg-3 col-sm-6" role="menu">
                <li>
                  <div class="col-md-12">
                    <h3>Login</h3>
                    <form action="[YOUR ACTION]" method="post" role="form" class="form-horizontal">
                      <input class="form-control" id="inputEmail1" placeholder="Email" type="email" style="margin-bottom:.5em">
                      <input class="form-control" id="inputPassword1" placeholder="Password" type="password" style="margin-bottom:.5em">
                      <div class="checkbox">
                        <label class="small"><input type="checkbox"> remember me</label>
                      </div>
                      <hr>
                      <input class="btn btn-primary btn-block" type="submit" name="commit" value="Sign In">
                    </form>
                  </div>
                </li>
              </ul>
              <ul class="col-lg-3 col-sm-6 list-unstyled" role="menu">
                <li><h3>Options</h3></li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li class="divider"></li>
                <li><a href="#" class="btn btn-primary pull-right">OK</a></li>
                <li><p class="small text-muted">small text here</p></li>
              </ul>
              <ul class="list-unstyled col-lg-3 col-sm-6" role="menu">
                <li><h3>More</h3></li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more link</a></li>
              </ul>
            </div>
          </li>

          <li><a href="#"><%=t('navbar.rating') %></a></li>
          <li><a href="#"><%=t('navbar.about') %></a></li>

        </ul>



        <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-user"></span>&nbsp;
                  <strong><%= current_user.name %></strong>
                  <span class="glyphicon glyphicon-chevron-down"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <div class="navbar-login">
                      <div class="row">
                        <div class="col-lg-4">
                          <p class="text-center">
                            <span class="glyphicon glyphicon-user icon-size"></span>
                          </p>
                        </div>
                        <div class="col-lg-8">
                          <p class="text-left"><strong><%= current_user.name %></strong></p>
                          <p class="text-left small"> <%= current_user.email %> </p>
                          <p class="text-left">

                            <%=link_to 'Өзгөртүү','/users/edit',class: 'btn btn-primary btn-block btn-sm' %>
                          </p>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <div class="navbar-login navbar-login-session">
                      <div class="row">
                        <div class="col-lg-12">
                          <p>
                            <%= link_to 'Чыгуу',destroy_user_session_path,method: :delete,class: 'btn btn-danger btn-block' %>
                          </p>
                        </div>
                      </div>
                    </div>
                  </li>


                </ul>
              </li>
            </ul>
        <% else %>

            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-user"></span>&nbsp;

                  <span class="glyphicon glyphicon-chevron-down"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <div class="navbar-login">
                      <div class="row">
                        <div class="col-lg-4">
                          <p class="text-center">
                            <span class="glyphicon glyphicon-user icon-size"></span>
                          </p>
                        </div>
                        <div class="col-lg-8">

                          <p class="text-left">

                            <%= link_to t('user.login'), new_user_session_path ,class: 'btn btn-primary btn-block btn-sm'%>
                          </p>

                          <p class="text-left">

                            <%= link_to t('user.sign_up'), new_user_registration_path ,class: 'btn btn-primary btn-block btn-sm'%>
                          </p>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="divider"></li>



                </ul>
              </li>
            </ul>

        <% end %>

      </div>&lt;!&ndash;/.nav-collapse &ndash;&gt;
    </div>
  </div>




<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>



-->