config/routes.rb
Rails.application.routes.draw do

  namespace :resource do
    resources :subjects
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'set_language/kyrgyz'

  get 'set_language/russian'

  get 'home/index'

  resources :forums, only: [:index, :new] do
    resources :questions do
      collection do
        post :vote_question_up
        post :vote_question_down
      end
      resources :answers,:comments do
        collection do
          post :vote_answer_up
          post :vote_answer_down
        end
        resources :answer_comments
      end
    end
  end



  resources :orts
  resources :profiles do
    collection do
      get :math
      get :analogy
      get :grammar
      get :reading
    end
  end

  namespace :ort do
    resources :infos

    resources :mains do
      collection do
        get :kolonka
        get :algebra
        get :analogy
        get :reading
        get :grammar
        get :email_ort
        post :check_reading
        post :check_kolonka
        post :check_algebra
        post :check_analogy
        post :check_grammar
        get :previous_grammar
        get :previous_reading
        get :previous_analogy
        get :previous_kolonka
        get :previous_algebra
        get :result
        get :start_over
      end
    end

    resources :grammar_quizzes do
      collection do
        post :check_grammar
        get :result
        get :previous_grammar
        get :start_over
      end
    end

    resources :reading_quizzes do
      collection do
        post :check_reading
        get :result
        get :previous_reading
        get :start_over
      end
    end

    resources :analogy_quizzes do
      collection do
        post :check_analogy
        get :result
        get :previous_analogy
        get :start_over
      end
    end

    resources :mathematic_quizzes do
      collection do
        post :check_part_one
        post :check_part_two
        get :result
        get :start_over
        get :home_page
        get :part_one
        get :part_two
        get :previous_part_one
        get :previous_part_two
      end
    end
  end

  devise_for :users, :controllers =>  { :omniauth_callbacks => "users/omniauth_callbacks" } do
    root 'admin'
  end

  as :user do
    get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
  end

  root to: 'home#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :answer_comments, dependent: :destroy
  validates :content, presence: true
  has_one :vote_answer, dependent: :destroy

  def to_s
    id
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:new,:vote_answer_down,:vote_answer_up, :create]

  def create
    @forum = Forum.find(params[:forum_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    @answer.save
    @answers = @question.answers
    to = @question.user
    @total = @question.answers.count
    AnswerMailer.new_answer_notification(current_user, @answer, to, request.url.chomp("/answers"), @question.title).deliver_now

  end

  def show
  end

  def edit

    @forum = Forum.find(params[:forum_id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])

  end

  def vote_answer_up

    @answer = Answer.find(params[:format])
    user = @answer.user
    vote = @answer.vote_answer

    if vote.nil? && user != current_user
      vote = @answer.build_vote_answer
      vote.users << current_user
      @answer.grade += 1

      if @answer.save!
        vote.save!
      end
    elsif !vote.nil? && !vote.users.exists?(current_user) && user != current_user
      vote.users << current_user
      @answer.grade += 1

      if @answer.save!
        vote.save!
      end
    elsif user == current_user
      @message = 'You cannot vote up your Answer!'
    end
  end

  def vote_answer_down
    @answer = Answer.find(params[:format])
    user = @answer.user
    vote = @answer.vote_answer

    if vote.nil? && user != current_user
      vote = @answer.build_vote_answer
      vote.users << current_user
      @answer.grade -= 1

      if @answer.save!
        vote.save!
      end
    elsif !vote.nil? && !vote.users.exists?(current_user) && user != current_user
      vote.users << current_user
      @answer.grade -= 1

      if @answer.save!
        vote.save!
      end
    elsif user == current_user
      @message = 'You cannot vote down your Answer!'
    end
  end

  def update
    @forum = Forum.find(params[:forum_id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])

    @answer.update_attributes(answer_params)

    @answers = @question.answers
  end

  def new
    @forum = Forum.find(params[:forum_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def delete
  end

  def destroy
    @forum = Forum.find(params[:forum_id])
    @question = Question.find(params[:question_id])
    @answers = @question.answers
    @answer = Answer.find(params[:id])
    @total = @question.answers.count


    @answer.destroy
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="product-index">
  <%= render 'answers/index' %>
</div>
<div id="ajax-modal" class="modal fade" tabindex="-1">
  <div class='modal-header'>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Campustask</h3>
  </div>
  <div class='modal-body'>
    <div class="modal-body-content"></div>
    <div class="ajax-loader"></div>
  </div>
  <div class='modal-footer'>
  </div>
</div>

app/views/answers/_edit.html.erb
<%= render 'answers/form'%>

app/views/answers/_form.html.erb
    <%= form_for [@forum,@question,@answer], remote: true, html: { style: "display:inline;" } do |f| %>
          <ul class="errors"></ul>

          <div class="form-group">

            <div data-no-turbolink>
            <%= f.cktext_area :content,rows: 10 , class: 'ckeditor'%>
              </div>
          </div>
          <%= f.submit t('forum.answers'), :class => 'btn btn-primary' %>
    <% end %>

app/views/answers/_index.html.erb
<% if @answers.size > 0 %>
    <% @answers.each do |answer| %>
        <hr>
        <div class="forum-post">
          <div class="fm-post-vote">
            <ul>
              <li><%= link_to vote_answer_up_forum_question_answers_path(@forum,@question,answer), remote: true, method: :post ,title: t('forum.answer.vote_up'), onclick: "voteUpAnswer(#{answer.id})" do %><i class="fa fa-caret-up fa-3x"></i><% end %></li>
              <li><span class="answer_vote_<%= answer.id %>"><%= answer.grade %></span></li>
              <li><%= link_to vote_answer_down_forum_question_answers_path(@forum,@question,answer), remote: true, method: :post ,title: t('forum.answer.vote_down'), onclick: "voteDownAnswer(#{answer.id})" do %><i class="fa fa-caret-down fa-3x"></i><% end %></li>
            </ul>
          </div>
          <div class="fm-post-body">
            <p class="lead">
              <a href="#"><%= answer.user.try(:name) %></a>
            </p>
            <p>
              <i class="fa fa-calendar"></i>
              <%= time_ago_in_words(answer.created_at) unless answer.created_at.blank?  %> <%= t('forum.time.ago') %>
            </p>
            <p>
              <%= answer.content.to_s.html_safe %>
            </p>
            <div class="tag-post">
              <% if user_signed_in? && answer.user_id == current_user.id %>
                  <%= link_to t('forum.delete'), [@forum,@question,answer], method: :delete, remote: true, class: "btn btn-primary btn-xs" %>
                  <%= link_to t('forum.edit'), edit_forum_question_answer_path(@forum,@question,answer), remote: true, class: "btn btn-primary btn-xs", data: { toggle: "modal", target: "#ajax-modal" ,'no-turbolink'=>true}  %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- First Comment -->
          <% if answer.answer_comments.count > 0 %>
              <div id="answer-comment-index-<%= answer.id %>">
                <% answer.answer_comments.each do |answer_comment| %>
                    <div id="answer-comment-show-<%= answer_comment.id %>">
                      <div class="media">
                        <div class="media-heading"></div>
                        <div>
                          <p> <%= answer_comment.content.to_s.html_safe %>  <span>-<a href="#"> <%= answer_comment.user.try(:name) %></a>  </span><span> <%= time_ago_in_words(answer_comment.created_at) unless answer_comment.created_at.blank? %> <%= t('forum.time.ago') %></span></p>
                          <div class="comment-meta">
                            <% if user_signed_in? && answer_comment.user_id == current_user.id %>
                                <span><%= link_to t('forum.delete'), [@forum,@question,answer,answer_comment],method: :delete , remote: true %></span>
                                <span><%= link_to t('forum.edit'), edit_forum_question_answer_answer_comment_path(@forum,@question,answer,answer_comment),remote: true %></span>
                            <% end %>
                          </div><!-- comment-meta -->
                        </div><!-- collapse -->
                      </div><!-- media -->
                      <div id="answer-comment-edit-<%= answer_comment.id %>"></div>
                    </div>
                <% end %>
              </div>
          <% else %>
              <div id="answer-comment-index-<%= answer.id %>"></div>
          <% end %>
          <!-- Second Comment --><!-- media -->
          <div id="answer-comment-new-<%= answer.id %>"></div>
          <% if answer.id %>
              <%= link_to t('forum.add_comment'), new_forum_question_answer_answer_comment_path(@forum,@question,answer) ,remote: true%>
          <% end %>
        </div>
    <% end %>
<% end %>
<!--<div class="form-group">
  <%= link_to 'New answer',new_forum_question_answer_path(@forum,@question),class: 'btn btn-info btn-lg' ,remote: true, data: { toggle: "modal", target: "#ajax-modal" ,'no-turbolink'=>true} %>
</div>-->

    <script>
      function voteUpAnswer(id) {
        var value = $('.answer_vote_' + id).text();
        <% if user_signed_in? %>
         value = parseInt(value) + 1;
        <% else %>
         alert('Please sign in!');
        <% end %>
        $('.answer_vote_'+id).text(value);
        value = '';
        console.log("voteUp() " + id);
      }

      function voteDownAnswer(id){
        var value = $('.answer_vote_' + id).text();
        <% if user_signed_in? %>
         value = parseInt(value) - 1;
        <% else %>
         alert('Please sign in!')
        <% end %>
        $('.answer_vote_'+id).text(value);
        value = '';
        console.log("voteDown() " + id);
      }
    </script>

app/views/answers/_new.html.erb
 <%= render 'answers/form' %>

app/views/answers/_save.js.erb
$("ul.errors").html("");
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".product-index").html("<%= j (render 'index') %>");
  $("#answers_count").html("<%= @total %>");
  CKEDITOR.instances["answer_content"].setData("");
<% end %>

app/views/answers/create.js.erb
<%= render 'answers/save' %>

app/views/answers/destroy.js.erb
<%= render 'answers/save' %>

app/views/answers/edit.js.erb
var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#ajax-modal';
$( 'textarea#answer_content').each( function() {
  CKEDITOR.replace( $(this).attr('id') );
});

//i set the title through a helper function
$(title).html('Edit ');
//hides the modal and shows the ajax content
$(loader).fadeToggle('fast', function() {
  $(loader).fadeOut('slow');
  $(content).html('<%= j render 'answers/edit' %>');
  $(modal).modal();
});
//brings the loader back up + gets rid of the content when linking to another controller method etc
$(content).on('click', dataRemote, function(){
  $(content).fadeOut('slow', function() {
    $(content).empty();
    $(loader).fadeIn('slow');
  });
});

app/views/answers/new.js.erb
var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#ajax-modal';

$( 'textarea#answer_content').each( function() {

  CKEDITOR.replace( $(this).attr('id') );

});

//i set the title through a helper function
$(title).html('New');
//hides the modal and shows the ajax content
$(loader).fadeToggle('fast', function() {
  $(loader).fadeOut('slow');
  $(content).html('<%= escape_javascript render 'answers/new' %>');
  $(modal).modal();
});
//brings the loader back up + gets rid of the content when linking to another controller method etc
$(content).on('click', dataRemote, function(){
  $(content).fadeOut('slow', function() {
    $(content).empty();
    $(loader).fadeIn('slow');
  });
});

app/views/answers/update.js.erb
<%= render 'answers/save' %>

app/views/answers/vote_answer_down.js.erb
$('.answer_vote_<%= @answer.id %>').html('<%= @answer.grade %>')

app/views/answers/vote_answer_up.js.erb
$('.answer_vote_<%= @answer.id %>').html('<%= @answer.grade %>')