config/routes.rb
Rails.application.routes.draw do

  namespace :resource do
    resources :subjects
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'set_language/kyrgyz'

  get 'set_language/russian'

  get 'home/index'

  resources :forums, only: [:index, :new] do
    resources :questions do
      collection do
        post :vote_question_up
        post :vote_question_down
      end
      resources :answers,:comments do
        collection do
          post :vote_answer_up
          post :vote_answer_down
        end
        resources :answer_comments
      end
    end
  end



  resources :orts
  resources :profiles do
    collection do
      get :math
      get :analogy
      get :grammar
      get :reading
    end
  end

  namespace :ort do
    resources :infos

    resources :mains do
      collection do
        get :kolonka
        get :algebra
        get :analogy
        get :reading
        get :grammar
        get :email_ort
        post :check_reading
        post :check_kolonka
        post :check_algebra
        post :check_analogy
        post :check_grammar
        get :previous_grammar
        get :previous_reading
        get :previous_analogy
        get :previous_kolonka
        get :previous_algebra
        get :result
        get :start_over
      end
    end

    resources :grammar_quizzes do
      collection do
        post :check_grammar
        get :result
        get :previous_grammar
        get :start_over
      end
    end

    resources :reading_quizzes do
      collection do
        post :check_reading
        get :result
        get :previous_reading
        get :start_over
      end
    end

    resources :analogy_quizzes do
      collection do
        post :check_analogy
        get :result
        get :previous_analogy
        get :start_over
      end
    end

    resources :mathematic_quizzes do
      collection do
        post :check_part_one
        post :check_part_two
        get :result
        get :start_over
        get :home_page
        get :part_one
        get :part_two
        get :previous_part_one
        get :previous_part_two
      end
    end
  end

  devise_for :users, :controllers =>  { :omniauth_callbacks => "users/omniauth_callbacks" } do
    root 'admin'
  end

  as :user do
    get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
  end

  root to: 'home#index'
end

app/controllers/ort/analogy_quizzes_controller.rb
class Ort::AnalogyQuizzesController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def index
    if session[:analogytest_id].nil?
      session[:analogytest_id] = params[:id]
      count_question
    end
    if session[:analogytest_id].nil?
      redirect_to orts_path
      return
    end
    session[:test] = "analogytest"
    @analogytest ||= Analogytest.find(session[:analogytest_id])
    @@analogies ||= @analogytest.analogytest_questions
    session[:question_timer] ||= @analogytest.timer
    session[:question_total] ||= @@analogies.length

    if session[:question_analogy_id].nil?
      session[:question_analogy_id] = @@analogies.first.id
    end
    if !session[:question_analogy_id].nil?
      @question = @@analogies.find(session[:question_analogy_id])
    end
    @id = question_answers_analogy["#{@question.id}"]
  end

  def previous_analogy
    @question = @@analogies.find(session[:question_analogy_id]).previous.first

    if !@question.nil? && @@analogies.exists?(@question)
      session[:question_analogy_id] = @question.id
      discount_question
      @id = question_answers_analogy["#{@question.id}"]
    end
  end

  def check_analogy
    question = @@analogies.find(session[:question_analogy_id])

    if question_answers_analogy.key?(question.id)
      question_answers_analogy[question.id] = params[:answer]
    else
      question_answers_analogy.store(question.id, params[:answer])
    end

    question_next = question.next.first

    if !question_next.nil? && @@analogies.exists?(question_next)
      session[:question_analogy_id] = question_next.id
    else
      session[:question_analogy_id] = nil
    end

    if session[:question_analogy_id].nil?
      render js: "window.location = '#{result_ort_analogy_quizzes_path}'"
    else
      count_question
      @question = question_next
      @id = question_answers_analogy["#{question_next.id}"]
    end
  end

  def start_over
    @result = 0
    @total = session[:question_total]

    question_answers_analogy.each do |key, value|
      question = @@analogies.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end
    destroy_session
  end

  def result
    @result = 0
    @total = session[:question_total]

    question_answers_analogy.each do |key, value|
      question = @@analogies.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    user_analogytest = current_user.user_analogytests.new
    user_analogytest.analogytest_id = session[:analogytest_id]
    user_analogytest.grade = @result
    user_analogytest.save!
    destroy_session
  end

  private
  def destroy_session
    session.delete(:analogytest_id)
    session.delete(:question_analogy_id)
    session.delete(:question_answers_analogy)

    session.delete(:count_question)
    session.delete(:question_total)
    session.delete(:question_timer)
    session.delete(:test)
    @@analogies = nil
  end
end

app/controllers/ort/grammar_quizzes_controller.rb
class Ort::GrammarQuizzesController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def index
    if session[:grammartest_id].nil?
      session[:grammartest_id] = params[:id]
      count_question
    end
    if session[:grammartest_id].nil?
      redirect_to orts_path
      return
    end
    session[:test] = "grammartest"

    @grammartest ||= Grammartest.find(session[:grammartest_id])
    @@grammars ||= @grammartest.grammartest_questions

    session[:question_timer] ||= @grammartest.timer
    session[:question_total] ||= @@grammars.length
    if session[:question_grammar_id].nil?
      session[:question_grammar_id] = @@grammars.first.id
    end
    if !session[:question_grammar_id].nil?
      @question = @@grammars.find(session[:question_grammar_id])
    end
    @id = question_answers_grammar["#{@question.id}"]
  end

  def previous_grammar
    @question = @@grammars.find(session[:question_grammar_id]).previous.first

    if !@question.nil? && @@grammars.exists?(@question)
      session[:question_grammar_id] = @question.id
      discount_question
      @id = question_answers_grammar["#{@question.id}"]
    end
  end

  def check_grammar
    question = @@grammars.find(session[:question_grammar_id])
    # store answers to session hash
    if question_answers_grammar.key?(question.id)
      question_answers_grammar[question.id] = params[:answer]
    else
      question_answers_grammar.store(question.id, params[:answer])
    end

    question_next = question.next.first

    if !question_next.nil? && @@grammars.exists?(question_next)
      session[:question_grammar_id] = question_next.id
    else
      session[:question_grammar_id] = nil
    end

    if session[:question_grammar_id].nil?
      render js: "window.location = '#{result_ort_grammar_quizzes_path}'"
    else
      count_question
      @question = question_next
      @id = question_answers_grammar["#{question_next.id}"]
    end
  end

  def start_over
    @result = 0
    @total = session[:question_total]

    question_answers_grammar.each do |key, value|
      question = @@grammars.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end
    destroy_session
  end

  def result
    @result = 0
    @total = session[:question_total]

    question_answers_grammar.each do |key, value|
      question = @@grammars.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    user_grammartest = current_user.user_grammartests.new
    user_grammartest.grammartest_id = session[:grammartest_id]
    user_grammartest.grade = @result
    user_grammartest.save!
    destroy_session
  end

  private
    def destroy_session
      session.delete(:grammartest_id)
      session.delete(:question_grammar_id)
      session.delete(:question_answers_grammar)

      session.delete(:count_question)
      session.delete(:question_total)
      session.delete(:question_timer)
      session.delete(:test)
      @@grammars = nil
    end
end

app/controllers/ort/infos_controller.rb
class Ort::InfosController < ApplicationController
  def index
  end
end

app/controllers/ort/mathematic_quizzes_controller.rb
class Ort::MathematicQuizzesController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def part_one

    if session[:mathtest_id].nil?
      session[:mathtest_id] = params[:id]
      count_question
    end

    if session[:mathtest_id].nil?
      redirect_to orts_path
      return
    end

    session[:test] = 'mathtest'

    @mathtest ||= Mathtest.find(session[:mathtest_id])

    @@part_twos ||= @mathtest.mathtest_part_twos
    @@part_ones ||= @mathtest.mathtest_part_ones

    session[:question_timer] ||= @mathtest.timer

    session[:question_total] ||= @@part_ones.length + @@part_twos.length

    if session[:question_part_one_id].nil? && session[:question_part_two_id].nil?
      session[:question_part_one_id] = @@part_ones.first.id
    end

    if !session[:question_part_one_id].nil?
      @question = @@part_ones.find(session[:question_part_one_id])
    end

    # this action redirec_to second part mathematics when part one finished
    if !session[:question_part_two_id].nil?
      redirect_to part_two_ort_mathematic_quizzes_path
      return
    end

    @id = question_answers_part_one["#{@question.id}"]
  end

  def part_two

    if session[:mathtest_id].nil?
      redirect_to orts_path
      return
    end

    @mathtest = Mathtest.find(session[:mathtest_id])
    @@part_twos ||= @mathtest.mathtest_part_twos

    if session[:question_part_two_id].nil?
      session[:question_part_two_id] = @@part_twos.first.id
      count_question
    end

    @question = @@part_twos.find(session[:question_part_two_id])
    @id = question_answers_part_two["#{@question.id}"]
  end

  def previous_part_one
    @question = @@part_ones.find(session[:question_part_one_id]).previous.first

    if !@question.nil? && @@part_ones.exists?(@question)
      session[:question_part_one_id] = @question.id
      discount_question
      @id = question_answers_part_one["#{@question.id}"]
    end
  end

  def previous_part_two
    @question = @@part_twos.find(session[:question_part_two_id]).previous.first

    if !@question.nil? && @@part_twos.exists?(@question)
      session[:question_part_two_id] = @question.id
      discount_question
      @id = question_answers_part_two["#{@question.id}"]
    end
  end

  def check_part_one
    question = @@part_ones.find(session[:question_part_one_id])

    # store answers to session hash
    if question_answers_part_one.key?(question.id)
      question_answers_part_one[question.id] = params[:answer]
    else
      question_answers_part_one.store(question.id, params[:answer])
    end

    question_next = question.next.first

    if !question_next.nil? && @@part_ones.exists?(question_next)
      session[:question_part_one_id] = question_next.id
    else
      session[:question_part_one_id] = nil
    end

    if session[:question_part_one_id].nil?
      render js: "window.location = '#{part_two_ort_mathematic_quizzes_path}'"
    else
      count_question
      @question = question_next
      @id = question_answers_part_one["#{question_next.id}"]
    end
  end

  def check_part_two
    question = @@part_twos.find(session[:question_part_two_id])

    if question_answers_part_two.key?(question.id)
      question_answers_part_two[question.id] = params[:answer]
    else
      question_answers_part_two.store(question.id, params[:answer])
    end

    question_next = question.next.first

    if !question_next.nil? && @@part_twos.exists?(question_next)
      session[:question_part_two_id] = question_next.id
    else
      session[:question_part_two_id] = nil
    end

    if session[:question_part_two_id].nil?
      render js: "window.location = '#{result_ort_mathematic_quizzes_path}'"
    else
      count_question
      @question = question_next
      @id = question_answers_part_two["#{question_next.id}"]
    end
  end

  def result
    @result = 0
    @total = session[:question_total]

    question_answers_part_two.each do |key, value|
      question = @@part_twos.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    question_answers_part_one.each do |key, value|
      question = @@part_ones.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    user_mathtest = current_user.user_mathtests.new
    user_mathtest.mathtest_id = session[:mathtest_id]
    user_mathtest.grade = @result
    user_mathtest.save!

    destroy_sessions
  end

  def start_over
    @result = 0
    @total = session[:question_total]

    question_answers_part_one.each do |key, value|
      question = @@part_ones.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    question_answers_part_two.each do |key, value|
      question = @@part_twos.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    destroy_sessions
  end

  private
    def destroy_sessions
      question_answers_part_two = nil
      question_answers_part_one = nil
      session.delete(:question_part_one_id)
      session.delete(:question_answers_part_one)
      session.delete(:question_answers_part_two)
      session.delete(:mathtest_id)
      session.delete(:question_part_two_id)
      session.delete(:count_question)
      session.delete(:question_total)
      session.delete(:question_timer)
      session.delete(:test)
      @@part_ones = nil
      @@part_twos = nil
    end
end

app/controllers/ort/reading_quizzes_controller.rb
class Ort::ReadingQuizzesController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def index
    if session[:readingtest_id].nil?
      session[:readingtest_id] = params[:id]
      count_question
    end

    if session[:readingtest_id].nil?
      redirect_to orts_path
      return
    end

    session[:test] = "readingtest"

    @readingtest ||= Readingtest.find(session[:readingtest_id])
    @@readings ||= @readingtest.readingtest_questions

    session[:question_timer] ||= @readingtest.timer
    session[:question_total] ||= @@readings.length

    if session[:question_reading_id].nil?
      session[:question_reading_id] = @@readings.first.id
    end

    if !session[:question_reading_id].nil?
      @question = @@readings.find(session[:question_reading_id])
      @article = @question.articletest
      @id = question_answers_reading["#{@question.id}"]
    end
  end

  def previous_reading
    @question = @@readings.find(session[:question_reading_id]).previous.first

    if !@question.nil?
      @article = @question.articletest
    end

    if !@question.nil? && @@readings.exists?(@question)
      session[:question_reading_id] = @question.id
      discount_question
      @id = question_answers_reading["#{@question.id}"]
    end
  end

  def check_reading
    question = @@readings.find(session[:question_reading_id])

    # store answers to session hash
    if question_answers_reading.key?(question.id)
      question_answers_reading[question.id] = params[:answer]
    else
      question_answers_reading.store(question.id, params[:answer])
    end

    question_next = question.next.first

    if !question_next.nil? && @@readings.exists?(question_next)
      session[:question_reading_id] = question_next.id
    else
      session[:question_reading_id] = nil
    end

    if session[:question_reading_id].nil?
      render js: "window.location = '#{result_ort_reading_quizzes_path}'"
    else
      count_question
      @question = question_next
      @article = @question.articletest
      @id = question_answers_reading["#{question_next.id}"]
    end
  end

  def result
    @result = 0
    @total = session[:question_total]

    question_answers_reading.each do |key, value|
      question = @@readings.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end

    user_readingtest = current_user.user_readingtests.new
    user_readingtest.readingtest_id = session[:readingtest_id]
    user_readingtest.grade = @result
    user_readingtest.save!
    destroy_session
  end

  def start_over
    @result = 0
    @total = session[:question_total]

    question_answers_reading.each do |key, value|
      question = @@readings.find(key)
      if question.answer == value
        @result = @result + 1
      end
    end
    destroy_session
  end

  private
    def destroy_session
      session.delete(:readingtest_id)
      session.delete(:question_reading_id)
      session.delete(:question_answers_reading)

      session.delete(:count_question)
      session.delete(:question_total)
      session.delete(:question_timer)
      session.delete(:test)

      @@readings = nil
    end
end

app/helpers/ort/analogy_quizzes_helper.rb
module Ort::AnalogyQuizzesHelper
end

app/helpers/ort/grammar_quizzes_helper.rb
module Ort::GrammarQuizzesHelper
end

app/helpers/ort/infos_helper.rb
module Ort::InfosHelper
end

app/helpers/ort/mains_helper.rb
module Ort::MainsHelper
end

app/helpers/ort/reading_quizzes_helper.rb
module Ort::ReadingQuizzesHelper
end

app/helpers/orts_helper.rb
module OrtsHelper
end

app/views/ort/reading_quizzes/_form.html.erb
<div class="testing-radio">
  <%= form_tag check_reading_ort_reading_quizzes_path, remote: :true do %>

      <div class="testing-radio-primary">
        <%= radio_button_tag("answer", 'А', checked = false, id: 'А' ) %>
        <%= label_tag "answer_А", @question.a.html_safe, for: 'А' %>
      </div>

      <div class="testing-radio-primary">
        <%= radio_button_tag("answer", 'Б', checked = false, id: 'Б' ) %>
        <%= label_tag "answer_Б", @question.b.html_safe, for: 'Б' %>
      </div>

      <div class="testing-radio-primary">
        <%= radio_button_tag("answer", 'В', checked = false, id: 'В' ) %>
        <%= label_tag "answer_В", @question.c.html_safe, for: 'В' %>
      </div>

      <div class="testing-radio-primary">
        <%= radio_button_tag("answer", 'Г', checked = false, id: 'Г' ) %>
        <%= label_tag "answer_Г", @question.d.html_safe, for: 'Г' %>
      </div>

      <center>
        <ul class="pagination">
          <li> <%= link_to "Мурунку суроо", previous_reading_ort_reading_quizzes_path, remote: true, class: 'btn btn-primary'%></li>
          <li> <%= submit_tag "Кийинки суроо", class: 'btn btn-primary' %></li>
        </ul>
      </center>

  <% end %>
</div>

app/views/ort/reading_quizzes/check_reading.js.erb
$('.question_content').html("<%= escape_javascript @question.content.html_safe %>");
$('.answer_form').html("<%= escape_javascript render 'ort/reading_quizzes/form' %>");
$("#<%=@id%>").attr('checked', true);
$('div#question_progress').width('<%= progress_question %>%');
$('div#question_progress').html('<%= (progress_question).to_s + '% Суроо иштелди' %>');
$('p#question_article').html('<%= escape_javascript @article.content.html_safe %>');

app/views/ort/reading_quizzes/index.html.erb
<section id="TestingBody">
  <section class="headline">
    <div class="container">
      <div class="row">
        <div class="header_right">
          <ul class="testing-btns">
            <li data-toggle="tooltip" title="Тестти Бүтүрүү жана Жыйынтыгын Корүү">
              <%= link_to start_over_ort_reading_quizzes_path, target: '_blank'  do %>
                  <i class="fa fa-external-link"></i><span> Токтот & Жыйынтык </span>
              <% end %>
            </li>
            <li data-toggle="tooltip" title="Сактоо жана Чыгуу">
              <%= link_to result_ort_reading_quizzes_path, target: '_blank'  do %>
                  <i class="fa fa-external-link"></i><span> Сакта & Чык</span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <section class="container">
    <div class="row mycontainer">
      <div class="col-sm-12 col-md-12 col-lg-12">
      </div>
      <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="row">
          <div class="test-qs-bd TestingLangText">
            <div class="test-qs-bd-inner">
              <aside id="TestingTimer">
                <button type="button" class="btn btn-info btn-sm btn-block" data-toggle="collapse" data-target="#timer"><%= t('quiz.timer') %></button>
                <div id="timer" class="collapse in">
                  <div id="DateCountdown" data-date="" style="width: 200px; height: 100px;"></div>
                </div>
              </aside>
              <p id="question_article">
                <%= @article.content.html_safe %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="row">
          <div class="test-qs-bd">
            <div class="progress">
              <div id="question_progress" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60"
                   aria-value min="0" aria-value max="100" style="width:80%">
              </div>
            </div>
            <div class="test-qs-bd-inner">
              <h4>Биринчи бөлүм</h4>
              <p>
                <div class="question_content"> <%= @question.content.html_safe %> </div>
              </p>
              <div class="answer_form">
                <%= render 'ort/reading_quizzes/form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</section>

<script>
  $('div#question_progress').width('<%= progress_question %>%');
  $('div#question_progress').html('<%= (progress_question).to_s + '% Суроо иштелди' %>');

  $("#<%=@id%>").attr('checked', true);

  var startTime = new Date();
  // this set timer count down seconds
  startTime.setSeconds(startTime.getSeconds() + <%= session[:question_timer] %>);

  console.log(getFormattedDate(startTime));

  var time;

  if (localStorage.getItem('readingtest') === null) {
    localStorage.setItem('readingtest', startTime);
    time = getFormattedDate(startTime);
    console.log("new Cookies readingtest setted !");
  } else {

    startTime = new Date(localStorage.getItem('readingtest'));

    console.log("Get readingtest Cookies")
    console.log('target ' + getFormattedDate(startTime));

    time = getFormattedDate(startTime);
  }


  var current_time = (new Date()).getTime();
  console.log("Current Time" + current_time);

  if (startTime < current_time) {
    console.log("Times up!");
    window.location.replace("<%= request.base_url %>/ort/reading_quizzes/result");

  }

  $('#DateCountdown').data('date', time).TimeCircles({
    count_past_zero: false,
    time: {Days: {show: false}, Hours: {show: false}}
  }).addListener(countdownComplete);
  // $("#CountDownTimer").TimeCircles({count_past_zero: false ,time: { Days: { show: false }, Hours: { show: false } }}).addListener(countdownComplete);

  function countdownComplete(unit, value, total) {
    if (total <= 0 && localStorage.getItem("readingtest") != null) {
      $('.question_time_up').fadeOut('slow').replaceWith("<h2><%= t('quiz.times_up') %></h2>");
      $(this).fadeOut('slow');

      // this destroy timer cookies
      localStorage.removeItem("readingtest")

      window.location.replace("<%= request.base_url %>/ort/reading_quizzes/result");
    }
    else if (localStorage.getItem('readingtest') == null){
      window.location.replace("<%= request.base_url %>");
    }
  }

  function getFormattedDate(date) {
    var year = date.getFullYear();
    var month = (1 + date.getMonth()).toString();
    month = month.length > 1 ? month : '0' + month;
    var day = date.getDate().toString();
    day = day.length > 1 ? day : '0' + day;
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var seconds = date.getSeconds();
    return year + '-' + month + '-' + day + ' ' + hours + ':' + minutes + ':' + seconds;
  }
</script>

app/views/ort/reading_quizzes/previous_reading.js.erb
$('.question_content').html("<%= j @question.content.html_safe %>");
$('.answer_form').html("<%= escape_javascript render 'ort/reading_quizzes/form' %>");
$("#<%=@id%>").attr('checked', true);
$('div#question_progress').width('<%= progress_question %>%');
$('div#question_progress').html('<%= (progress_question).to_s + '% Суроо иштелди' %>');
$('p#question_article').html('<%= escape_javascript @article.content.html_safe %>');

app/views/ort/reading_quizzes/result.html.erb
<div id="container" style="width: 100%;">
  <canvas id="canvas"></canvas>
</div>

<%= link_to 'Негизги бет', root_path, class: 'btn btn-primary' %>

<script>

  var randomScalingFactor = function() {
    return (Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100);
  };
  var randomColorFactor = function() {
    return Math.round(Math.random() * 255);
  };
  var randomColor = function() {
    return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',.7)';
  };

  var barChartData = {
    labels: ["", "<%= current_user.name %>","Жалпы суроо"],
    datasets: [{
      label: 'Окуу жана Түшүнүү Жыйынтык',
      backgroundColor: "rgba(220,220,220,0.5)",
      data: [0,<%=@result%>,<%=@total%>]
    }]

  };

  window.onload = function() {
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myBar = new Chart(ctx, {
      type: 'bar',
      data: barChartData,
      options: {
        // Elements options apply to all of the options unless overridden in a dataset
        // In this case, we are setting the border of each bar to be 2px wide and green
        elements: {
          rectangle: {
            borderWidth: 2,
            borderColor: 'rgb(0, 255, 0)',
            borderSkipped: 'bottom'
          }
        },
        responsive: true,
        legend: {
          position: 'top',
        },
        title: {
          display: true,
          text: "<%= current_user.name %>"+" Окуу жана Түшүнүү Жыйынтыгы !"
        }
      }
    });

  };

</script>

<script>
  // this destroy count down timer cookies
  localStorage.removeItem("readingtest");
  console.log("readingtest cookies destroyed!")
</script>

app/views/ort/reading_quizzes/start_over.html.erb
<div id="container" style="width: 100%;">
  <canvas id="canvas"></canvas>
</div>

<%= link_to 'Негизги бет', root_path, class: 'btn btn-primary' %>

<script>

  var randomScalingFactor = function() {
    return (Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100);
  };
  var randomColorFactor = function() {
    return Math.round(Math.random() * 255);
  };
  var randomColor = function() {
    return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',.7)';
  };

  var barChartData = {
    labels: ["", "<%= current_user.name %>","Жалпы суроо"],
    datasets: [{
      label: 'Окуу жана Түшүнүү Жыйынтык',
      backgroundColor: "rgba(220,220,220,0.5)",
      data: [0,<%=@result%>,<%=@total%>]
    }]

  };

  window.onload = function() {
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myBar = new Chart(ctx, {
      type: 'bar',
      data: barChartData,
      options: {
        // Elements options apply to all of the options unless overridden in a dataset
        // In this case, we are setting the border of each bar to be 2px wide and green
        elements: {
          rectangle: {
            borderWidth: 2,
            borderColor: 'rgb(0, 255, 0)',
            borderSkipped: 'bottom'
          }
        },
        responsive: true,
        legend: {
          position: 'top',
        },
        title: {
          display: true,
          text: "<%= current_user.name %>"+" Окуу жана Түшүнүү Жыйынтыгы !"
        }
      }
    });

  };

</script>

<script>
  // this destroy count down timer cookies
  localStorage.removeItem("readingtest");
  console.log("readingtest cookies destroyed!")
</script>